CREATE TABLE `ELECTRICVALUES` (
  `Comsume` decimal(7,3) DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `TEXT_MESSAGE` TEXT DEFAULT NULL,
  `POWERFAILURE_LOG` TEXT DEFAULT NULL,
  `Time` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
